version: "3.8"
services:
    database:
        image: "postgres"
        container_name: "postgres_database"
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: stock-market
        ports:
            -   "5432:5432"
        volumes:
            -   postgres_storage:/var/lib/postgresql/data
volumes:
    postgres_storage: