[project]
name = "market-miner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.1",
    "pandas>=2.3.1",
    "prisma>=0.15.0",
    "selenium>=4.34.2",
    "webdriver-manager>=4.0.2",
]
